Repository aws-controllers-k8s/rds-controller, pull requests merged in 2022-08, with the labels that each got.

#104 v0.0.30 release
  apis/v1alpha1/ack-generate-metadata.yaml
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/templates/deployment.yaml
  helm/values.yaml
Labels: needs-ok-to-test

#105 Support RDSProxy CRD
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/db_proxy.go
  apis/v1alpha1/enums.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/rds.services.k8s.aws_dbproxies.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/rds.services.k8s.aws_dbproxies.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  pkg/resource/db_proxy/delta.go
  pkg/resource/db_proxy/descriptor.go
  pkg/resource/db_proxy/identifiers.go
  pkg/resource/db_proxy/manager.go
  pkg/resource/db_proxy/manager_factory.go
  pkg/resource/db_proxy/references.go
  pkg/resource/db_proxy/resource.go
  pkg/resource/db_proxy/sdk.go
  pkg/resource/db_proxy/tags.go
Labels: approved

#106 support tag updates for DBInstance
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/db_instance.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
  generator.yaml
  helm/crds/rds.services.k8s.aws_dbinstances.yaml
  pkg/resource/db_cluster/delta.go
  pkg/resource/db_cluster_parameter_group/delta.go
  pkg/resource/db_instance/delta.go
  pkg/resource/db_instance/hooks.go
  pkg/resource/db_instance/sdk.go
  pkg/resource/db_parameter_group/delta.go
  pkg/resource/db_subnet_group/delta.go
  templates/hooks/db_instance/delta_pre_compare.go.tpl
  templates/hooks/db_instance/sdk_read_many_post_set_output.go.tpl
  templates/hooks/db_instance/sdk_update_pre_build_request.go.tpl
  test/e2e/db_instance.py
  test/e2e/resources/db_instance_postgres14_t3_micro.yaml
  test/e2e/tests/test_db_instance.py
Labels: approved, lgtm

#109 correct delta_pre_compare for DBInstance
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/db_instance/delta.go
  pkg/resource/db_instance/hooks.go
  pkg/resource/db_instance/sdk.go
  templates/hooks/db_instance/delta_pre_compare.go.tpl
  test/e2e/tests/test_db_instance.py
Labels: approved, lgtm

#111 Fix `computeTagsDelta` function
  pkg/resource/db_instance/hooks.go
Labels: approved

#112 Comment out last multiAZ flag assert
  test/e2e/tests/test_db_instance.py
Labels: approved, lgtm

#113 Update `computeTagsDelta` function
  pkg/resource/db_cluster/hooks.go
  pkg/resource/db_cluster_parameter_group/hooks.go
  pkg/resource/db_instance/hooks.go
  pkg/resource/db_parameter_group/hooks.go
  pkg/resource/db_subnet_group/hooks.go
  pkg/util/tags.go
  pkg/util/tags_test.go
Labels: approved, lgtm

#114 remove dev preview from olm file in preparation for GA
  olm/olmconfig.yaml
Labels: lgtm, needs-ok-to-test, do-not-merge/hold

#115 Add e2e test for rdsproxy
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/db_proxy/hooks.go
  test/e2e/bootstrap_resources.py
  test/e2e/db_proxy.py
  test/e2e/resources/db_proxy.yaml
  test/e2e/service_bootstrap.py
  test/e2e/tests/test_db_proxy.py
Labels: approved, lgtm

#116 Add E2e tests global cluster
  test/e2e/global_cluster.py
  test/e2e/resources/global_cluster.yaml
  test/e2e/tests/test_global_cluster.py
Labels: approved, lgtm
