Repository aws-controllers-k8s/rds-controller, pull requests merged in 2022-06, with the labels that each got.

#80 Remove DBSecurityGroup CRD from rds-controller
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/db_instance.go
  apis/v1alpha1/db_security_group.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
  config/crd/bases/rds.services.k8s.aws_dbsecuritygroups.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/rds.services.k8s.aws_dbinstances.yaml
  helm/crds/rds.services.k8s.aws_dbsecuritygroups.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  olm/olmconfig.yaml
  pkg/resource/db_instance/delta.go
  pkg/resource/db_instance/sdk.go
  pkg/resource/db_security_group/delta.go
  pkg/resource/db_security_group/descriptor.go
  pkg/resource/db_security_group/identifiers.go
  pkg/resource/db_security_group/manager.go
  pkg/resource/db_security_group/manager_factory.go
  pkg/resource/db_security_group/references.go
  pkg/resource/db_security_group/resource.go
  pkg/resource/db_security_group/sdk.go
  test/e2e/resources/db_security_group_simple.yaml
  test/e2e/tests/test_db_security_group.py
Labels: approved, lgtm

#83 Allow major version upgrade by setting AllowMajorVersionUpgrade to true
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/db_cluster/custom_update.go
  pkg/resource/db_instance/sdk.go
Labels: approved, lgtm

#87 Ignore several fields for rds modify call when no delta in yaml file
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/db_instance/sdk.go
  templates/hooks/db_instance/sdk_update_post_build_request.go.tpl
Labels: approved

#88 Remove DBParameterGroupNotFound and DBSubnetGroupNotFoundFault from terminal exception
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/db_cluster/sdk.go
  pkg/resource/db_instance/sdk.go
Labels: approved, lgtm

#89 Fix rename of DBParameterGroup family for AdoptedResource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/db_parameter_group/sdk.go
  pkg/resource/db_subnet_group/sdk.go
Labels: approved, lgtm

#90 Update ACK runtime to v0.19.1
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  cmd/controller/main.go
  config/controller/deployment.yaml
  config/controller/kustomization.yaml
  generator.yaml
  go.mod
  go.sum
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/values.schema.json
  helm/values.yaml
  pkg/resource/db_cluster/manager.go
  pkg/resource/db_cluster/references.go
  pkg/resource/db_cluster/sdk.go
  pkg/resource/db_cluster/tags.go
  pkg/resource/db_cluster_parameter_group/manager.go
  pkg/resource/db_cluster_parameter_group/sdk.go
  pkg/resource/db_cluster_parameter_group/tags.go
  pkg/resource/db_instance/manager.go
  pkg/resource/db_instance/references.go
  pkg/resource/db_instance/sdk.go
  pkg/resource/db_instance/tags.go
  pkg/resource/db_parameter_group/manager.go
  pkg/resource/db_parameter_group/sdk.go
  pkg/resource/db_parameter_group/tags.go
  pkg/resource/db_subnet_group/manager.go
  pkg/resource/db_subnet_group/sdk.go
  pkg/resource/db_subnet_group/tags.go
  pkg/resource/global_cluster/manager.go
  pkg/resource/global_cluster/sdk.go
  test/e2e/tag.py
  test/e2e/tests/test_db_cluster.py
  test/e2e/tests/test_db_cluster_parameter_group.py
  test/e2e/tests/test_db_parameter_group.py
  test/e2e/tests/test_db_subnet_group.py
Labels: approved, lgtm

#81 Apply RDS API updates to CRD
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/db_cluster.go
  apis/v1alpha1/db_cluster_parameter_group.go
  apis/v1alpha1/db_instance.go
  apis/v1alpha1/db_parameter_group.go
  apis/v1alpha1/db_subnet_group.go
  apis/v1alpha1/enums.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rds.services.k8s.aws_dbclusterparametergroups.yaml
  config/crd/bases/rds.services.k8s.aws_dbclusters.yaml
  config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
  config/crd/bases/rds.services.k8s.aws_dbparametergroups.yaml
  config/crd/bases/rds.services.k8s.aws_dbsubnetgroups.yaml
  go.mod
  go.sum
  helm/crds/rds.services.k8s.aws_dbclusterparametergroups.yaml
  helm/crds/rds.services.k8s.aws_dbclusters.yaml
  helm/crds/rds.services.k8s.aws_dbinstances.yaml
  helm/crds/rds.services.k8s.aws_dbparametergroups.yaml
  helm/crds/rds.services.k8s.aws_dbsubnetgroups.yaml
  pkg/resource/db_cluster/delta.go
  pkg/resource/db_cluster/sdk.go
  pkg/resource/db_instance/delta.go
  pkg/resource/db_instance/sdk.go
  pkg/resource/db_subnet_group/sdk.go
Labels: ok-to-test, approved, lgtm

#91 Ignore NetworkType param if no change, not consider diff when engine version diff in minor version
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/db_instance/delta.go
  pkg/resource/db_instance/hooks.go
  pkg/resource/db_instance/sdk.go
  templates/hooks/db_instance/delta_pre_compare.go.tpl
  templates/hooks/db_instance/sdk_update_post_build_request.go.tpl
Labels: approved

#93 v0.0.26 release
  apis/v1alpha1/ack-generate-metadata.yaml
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm, needs-ok-to-test
